config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :cans

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  has_many :cans
  validates :name, presence: true
  validates :address, presence: true
  validates :website, presence: true
end

app/models/can.rb
class Can < ApplicationRecord
  belongs_to :brewery
  belongs_to :hop, optional: true
  validates :name, presence: true
  validates :abv, presence: true
  has_one_attached :photo
end

app/models/hop.rb
class Hop < ApplicationRecord
  belongs_to :can, optional: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/cans_controller.rb
class CansController < ApplicationController
  def new
    @can = Can.new
  end

  def create
    @can = Can.new(can_params)
     if @can.save
      redirect_to cans_path
     else
    render :new
    end
  end

  def index
    @cans = Can.all
  end

  def show
  end


  def can_params
    params.require(:can).permit(:name, :abv, :photo, :brewery_id, :hop_id)
  end
end

app/controllers/hops_controller.rb
class HopsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/breweries/create.html.erb
<h1>Breweries#create</h1>
<p>Find me in app/views/breweries/create.html.erb</p>

app/views/breweries/destroy.html.erb
<h1>Breweries#destroy</h1>
<p>Find me in app/views/breweries/destroy.html.erb</p>

app/views/breweries/edit.html.erb
<h1>Breweries#edit</h1>
<p>Find me in app/views/breweries/edit.html.erb</p>

app/views/breweries/index.html.erb
<h1>Breweries#index</h1>
<p>Find me in app/views/breweries/index.html.erb</p>

app/views/breweries/new.html.erb
<h1>Breweries#new</h1>
<p>Find me in app/views/breweries/new.html.erb</p>

app/views/breweries/show.html.erb
<h1>Breweries#show</h1>
<p>Find me in app/views/breweries/show.html.erb</p>

app/views/breweries/update.html.erb
<h1>Breweries#update</h1>
<p>Find me in app/views/breweries/update.html.erb</p>

app/views/cans/create.html.erb
<h1>Cans#create</h1>
<p>Find me in app/views/cans/create.html.erb</p>

app/views/cans/destroy.html.erb
<h1>Cans#destroy</h1>
<p>Find me in app/views/cans/destroy.html.erb</p>

app/views/cans/edit.html.erb
<h1>Cans#edit</h1>
<p>Find me in app/views/cans/edit.html.erb</p>

app/views/cans/index.html.erb
<h1>Cans</h1>

<div class="cans-container">
    <% @cans.each do |can| %>
  <div class="cans-card">
      <%= link_to can_path(can)%>
      <div class="can-img">
         <%= cl_image_tag(can.photo.key, :transformation=>[{:width=>220, :crop=>"fill", :effect=>"saturation:50", :radius=>5, :responsive => true}]) %>
      </div>
    <div class="can-info">
      <ul>
        <li><%= can.name %></li>
        <li><%= can.abv %></li>
        <li><%= can.brewery.name %></li>
      </ul>

     </div>
    <% end %>
  </div>
</div>

app/views/cans/new.html.erb
<h1>Cans#new</h1>
<p>Find me in app/views/cans/new.html.erb</p>

<%= simple_form_for @can do |f| %>
<%= f.label :name, "name" %>
<%= f.text_field :name %>
<%= f.label :abv, "abv %" %>
<%= f.number_field :abv %>
<%= f.association :brewery, label_method: :name %>
<%= f.association :hop %>
<%= f.input :photo, as: :file %>
<%= f.button :submit %>

<% end %>

app/views/cans/show.html.erb
<h1>Cans#show</h1>
<p>Find me in app/views/cans/show.html.erb</p>

app/views/cans/update.html.erb
<h1>Cans#update</h1>
<p>Find me in app/views/cans/update.html.erb</p>

app/views/hops/create.html.erb
<h1>Hops#create</h1>
<p>Find me in app/views/hops/create.html.erb</p>

app/views/hops/new.html.erb
<h1>Hops#new</h1>
<p>Find me in app/views/hops/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content text-center">
        <h1 style="color:white">Cans</h1>
        <%= link_to "Enter", cans_path, class: "btn-enter" %>
    </div>
    <p></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>